### ISSUE TITLE
Non-terminating errors while building 03 Full Lab with DSC and TFS.ps1

### ISSUE THREAD

**Issue by sundmoon** [AutomatedLab/DscWorkshop#10]
15:16:27|00:39:28|00:00:00.000| - Installing Certificate Servers
15:16:27|00:39:28|00:00:00.000|   - Machines with Root CA role to be installed: 'DSCCASQL01'
15:16:27|00:39:28|00:00:00.005|     - Waiting for machines to start up..
15:16:55|00:39:55|00:00:27.712|     - Waiting for Root CA(s) to complete installation.....
15:17:25|00:40:26|00:00:58.597|     - Publishing certificates from CA servers to all online machines....
15:17:49|00:40:50|00:01:22.473|     - Finished installation of Root CAs
15:17:49|00:40:50|00:01:22.552|   - Done
15:17:57|00:40:57|00:40:39.910| - .......
15:19:24|00:42:25|00:00:00.001| - Installing DSC Pull Servers
15:19:24|00:42:25|00:00:00.045|   - Starting Pull Servers and waiting until they are ready..
15:19:30|00:42:30|00:00:05.436|   - Routing Role detected, installing DSC in online mode.
15:19:45|00:42:46|00:00:20.895|   - All DSC Pull Servers can reach the internet.
15:19:45|00:42:46|00:00:21.168|   - Waiting for machines to startup..
15:19:53|00:42:54|00:00:00.000|   - Executing lab command activity: 'Duplicating CA template WebServer -> DscPullSsl' on machines 'DSCCASQL01'
15:19:53|00:42:54|00:00:00.011|     - Waiting for completion
15:19:57|00:42:58|00:00:04.162|     - Activity done
15:20:08|00:43:09|00:00:00.000|   - Executing lab command activity: 'Publishing CA template DscPullSsl' on machines 'DSCCASQL01'
15:20:08|00:43:09|00:00:00.007|     - Waiting for completion
15:20:09|00:43:10|00:00:00.661|     - Activity done
15:20:11|00:43:11|00:00:00.000|   - Executing lab command activity: 'Duplicating CA template CEPEncryption -> DscMofEncryption' on machines 'DSCCASQL01'
15:20:11|00:43:11|00:00:00.005|     - Waiting for completion
15:20:14|00:43:15|00:00:03.587|     - Activity done
15:20:25|00:43:26|00:00:00.000|   - Executing lab command activity: 'Publishing CA template DscMofEncryption' on machines 'DSCCASQL01'
15:20:25|00:43:26|00:00:00.006|     - Waiting for completion
15:20:26|00:43:27|00:00:00.801|     - Activity done
15:20:26|00:43:27|00:00:00.000|   - Executing lab command activity: 'Setup Dsc Pull Server 1' on machines 'DSCPULL01'
15:20:26|00:43:27|00:00:00.005|     - Activity started in background
15:20:32|00:43:32|00:01:07.389|   - Activity started in background
15:22:03|00:45:03|00:00:00.000| - Installing software package 'G:\LabSources\SoftwarePackages\AccessDatabaseEngine.exe' on machines 'DSCPULL01'
15:22:03|00:45:03|00:00:00.078|   - Copying files and initiating setup on 'DSCPULL01' and waiting for completion..
15:22:14|00:45:15|00:00:11.868|   - Installation done
15:22:15|00:45:16|00:00:00.000| - Executing lab command activity: 'Requesting certificate for template 'DscMofEncryption'' on machines 'DSCPULL01'
15:22:15|00:45:16|00:00:00.006|   - Waiting for completion
15:22:17|00:45:18|00:00:01.799|   - Activity done
15:22:18|00:45:19|00:00:00.000| - Executing lab command activity: 'Requesting certificate for template 'DscPullSsl'' on machines 'DSCPULL01'
15:22:18|00:45:19|00:00:00.011|   - Waiting for completion
15:22:19|00:45:20|00:00:00.688|   - Activity done
15:22:19|00:45:20|00:00:00.000| - Executing lab command activity: 'Setting up DSC Pull Server on 'DSCPULL01'' on machines 'DSCPULL01'
15:22:19|00:45:20|00:00:00.011|   - Activity started in background
15:22:19|00:45:20|00:45:02.490| - Activity started in background
15:22:19|00:45:20|00:45:08.434| Waiting for configuration of DSC Pull Server to complete....
15:22:48|00:45:48|00:45:36.792| Waiting for installation of IIS web admin tools to complete
**Method invocation failed because [System.Collections.Generic.List`1[[AutomatedLab.Disk, AutomatedLab, Version=5.0.3.27, Culture=neutral, PublicKeyToken=null]]] does not contain a method named 'Export'.**
At C:\Program Files\WindowsPowerShell\Modules\AutomatedLab\5.0.3.27\AutomatedLab.psm1:616 char:5
+     $lab.Disks.Export($lab.DiskDefinitionFiles[0].Path)
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : MethodNotFound

**Method invocation failed because [System.Collections.Generic.List`1[[AutomatedLab.Disk, AutomatedLab, Version=5.0.3.27, Culture=neutral, PublicKeyToken=null]]] does not contain a method named 'AddFromFile'.**
At C:\Program Files\WindowsPowerShell\Modules\AutomatedLab\5.0.3.27\AutomatedLab.psm1:622 char:5
+     $lab.Disks.AddFromFile($lab.DiskDefinitionFiles[0].Path)
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : MethodNotFound

15:22:52|00:45:53|00:45:41.680| Done
15:22:52|00:45:53|00:00:00.000| Installing SQL Servers
15:22:53|00:45:53|00:00:00.057| - Machines to have SQL Server 2017 installed: 'DSCCASQL01'
15:22:53|00:45:53|00:00:00.134| - Starting machines 'DSCCASQL01'..
15:23:08|00:46:09|00:00:15.463| - Waiting for pre-requisite .Net 3.5 Framework to finish installation on machines 'DSCCASQL01'......Done
15:25:24|00:48:25|00:02:31.441| - Waiting for installation of SQL server to complete on machines 'DSCCASQL01'...............
15:30:54|00:53:55|00:08:01.611| - All SQL Servers 'DSCCASQL01' have now been installed and restarted. Waiting for these to be ready...
15:30:58|00:53:59|00:08:05.919| - Installing SQL Server Management Studio on 'DSCCASQL01' in the background.
15:31:05|00:54:06|00:08:12.708| - Waiting for SQL Server Management Studio installation jobs to finish.........
15:34:43|00:57:44|00:11:50.928| - Done
15:34:43|00:57:44|00:00:00.000| Installing Web Servers
15:34:43|00:57:44|00:00:00.010| - Machines to have Web Server role installed: 'DSCPULL01, DSCWeb01, DSCWeb02'
15:34:43|00:57:44|00:00:00.055| - Waiting for machines to start up.....
15:35:52|00:58:53|00:01:08.717| - Waiting for Web Server role to complete installation......
15:38:33|01:01:34|00:03:50.048| - Done
15:38:34|01:01:34|00:00:00.000| Installing Team Foundation Server environment
15:38:34|01:01:34|00:00:00.015| Machines to have TFS or the build agent installed: 'DSCPULL01, DSCTFS01'
15:38:42|01:01:43|00:00:08.346| .......
15:40:22|01:03:23|00:01:48.330| ....
15:41:27|01:04:27|00:00:00.000| Waiting for job(s) to complete with ID(s): 654

**Comment by sundmoon** [comment]
15:46:43|01:09:44|00:05:16.240| - Job(s) no longer running
15:46:47|01:09:48|00:08:13.805| ....
15:47:36|01:10:37|00:00:00.000| Installing Windows Feature(s) 'Web-Mgmt-Tools' on computer(s) 'DSCTFS01'
15:47:36|01:10:37|00:00:00.004| - Windows Feature(s) is being installed in the background
15:47:48|01:10:49|00:09:14.455| Waiting for installation of IIS web admin tools to complete.Executing lab command activity: 'Requesting certificate for template 'WebServer'' on machines 'DSCTFS01'
15:47:50|01:10:51|00:00:00.009| - Waiting for completion
15:48:00|01:11:01|00:00:10.012| - Activity done
**Remove-Item : Cannot find path 'C:\ProgramData\AutomatedLab\Labs\psconf18\Disks.xml' because it does not exist.**
At C:\Program Files\WindowsPowerShell\Modules\AutomatedLab\5.0.3.27\AutomatedLab.psm1:613 char:5
+     Remove-Item -Path $lab.DiskDefinitionFiles[0].Path
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\ProgramData\...onf18\Disks.xml:String) [Remove-Item], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.RemoveItemCommand

**Method invocation failed because [System.Collections.Generic.List`1[[AutomatedLab.Disk, AutomatedLab, Version=5.0.3.27, Culture=neutral, PublicKeyToken=null]]] does not contain a method named 'Export'.**
At C:\Program Files\WindowsPowerShell\Modules\AutomatedLab\5.0.3.27\AutomatedLab.psm1:616 char:5
+     $lab.Disks.Export($lab.DiskDefinitionFiles[0].Path)
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : MethodNotFound

**Method invocation failed because [System.Collections.Generic.List`1[[AutomatedLab.Disk, AutomatedLab, Version=5.0.3.27, Culture=neutral, PublicKeyToken=null]]] does not contain a method named 'AddFromFile'.**
At C:\Program Files\WindowsPowerShell\Modules\AutomatedLab\5.0.3.27\AutomatedLab.psm1:622 char:5
+     $lab.Disks.AddFromFile($lab.DiskDefinitionFiles[0].Path)
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : MethodNotFound

15:48:01|01:11:01|00:00:00.000| Waiting for job(s) to complete with ID(s): 682
15:48:35|01:11:36|00:00:34.034| - Job(s) no longer running
15:48:36|01:11:37|00:00:00.000| Waiting for job(s) to complete with ID(s): 687
15:48:45|01:11:46|00:00:09.018| - Job(s) no longer running
15:48:46|01:11:46|00:10:11.999| Team Foundation Server environment deployed
15:48:46|01:11:46|00:00:00.000| Starting remaining machines
15:48:46|01:11:46|00:00:00.006| - Waiting for machines to start up....

**Comment by raandree** [comment]
Did the deployment work in general?

I am chasing the bug
```
Method invocation failed because [System.Collections.Generic.List`1[[AutomatedLab.Disk, AutomatedLab, Version=5.0.3.27, Culture=neutral, PublicKeyToken=null]]] does not contain a method named 'AddFromFile'.
```
since quite a while. It should not have an effect on the deployment and is just ugly.

**Comment by raandree** [comment]
This should be fixed quite some time ago.
