### ISSUE TITLE
Please explain a bit more how to start experimenting with '02 Intermediate Lab..' only

### ISSUE THREAD

**Issue by sundmoon** [AutomatedLab/DscWorkshop#11]
Waiting for  https://github.com/AutomatedLab/AutomatedLab/issues/402 
Please elaborate how to make use of the intermediate stage

First, I wonder if it is set up right

PS I:\LabSources\SampleScripts\Introduction> invoke-labcommand {Get-DscLocalConfigurationManager} -comp DSCPULL01 -PassThru

17:19:11|03:00:18|00:00:00.000| - Executing lab command activity: '<unnamed>' on machines 'DSCPULL01'
17:19:11|03:00:18|00:00:00.010|   - Waiting for completion
17:19:11|03:00:19|00:00:00.448|   - Activity done

ActionAfterReboot              : ContinueConfiguration
AgentId                        : 4B4664B5-794D-11E8-B7ED-0017FA000007
AllowModuleOverWrite           : False
CertificateID                  :
ConfigurationDownloadManagers  : {}
ConfigurationID                :
ConfigurationMode              : ApplyAndMonitor
ConfigurationModeFrequencyMins : 15
Credential                     :
DebugMode                      : {NONE}
DownloadManagerCustomData      :
DownloadManagerName            :
LCMCompatibleVersions          : {1.0, 2.0}
LCMState                       : Idle
LCMStateDetail                 :
LCMVersion                     : 2.0
StatusRetentionTimeInDays      : 10
SignatureValidationPolicy      : NONE
SignatureValidations           : {}
MaximumDownloadSizeMB          : 500
PartialConfigurations          :
RebootNodeIfNeeded             : False
RefreshFrequencyMins           : 30
RefreshMode                    : **PUSH**
ReportManagers                 : {}
ResourceModuleManagers         : {}
PSComputerName                 : DSCPULL01
PSComputerName                 : DSCPULL01

**Comment by raandree** [comment]
Sorry for the late response.

Yes, the config of the pull server's LCM is correct. The DSC nodes are pulling, the pull server has received its configuration via push.

I am currently extending and changing some structure of the project.
