### ISSUE TITLE
Unable to create the DSCCASQL01 Server - 03 Full Lab with DSC and TFS Azure.ps1

### ISSUE THREAD

**Issue by GradualUnicycle** [AutomatedLab/DscWorkshop#2]
**having som issues running the '03 Full Lab with DSC and TFS Azure.ps1'.  I get the following error msg:**

Failed to create the following Azure machines: DSCCASQL01'. For further information take a look at the background job's result (Get-Job, Receive-Job)
At C:\Program Files\WindowsPowerShell\Modules\AutomatedLab\5.0.2.0\AutomatedLabVirtualMachines.psm1:99 char:9
+         throw "Failed to create the following Azure machines: $machin ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Failed to creat...b, Receive-Job):String) [], RuntimeException
    + FullyQualifiedErrorId : Failed to create the following Azure machines: DSCCASQL01'. For further information take a look at the background job's result (Get-Job, Receive-Job)

**when i do a Get-Job | Receive-Job i get the following:**

One or more errors occured during VM creation.
System.Management.Automation.ActionPreferenceStopException: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The platform
 image 'MicrosoftSQLServer:SQL2017-WS2016-BYOL:Enterprise:latest' is not available. Verify that all fields in the storage profile are correct.
ErrorCode: ImageNotFound
**ErrorMessage: The platform image 'MicrosoftSQLServer:SQL2017-WS2016-BYOL:Enterprise:latest' is not available.** Verify that all fields in the storage profile are correct.
StatusCode: 404
ReasonPhrase: Not Found
OperationID : faba9988-5d46-44cf-8414-261371159398
   ved System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   ved System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   ved System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   ved System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
    + CategoryInfo          : OperationStopped: (One or more err...tedFrame frame):String) [], RuntimeException
    + FullyQualifiedErrorId : One or more errors occured during VM creation.
    System.Management.Automation.ActionPreferenceStopException: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The pla
   tform image 'MicrosoftSQLServer:SQL2017-WS2016-BYOL:Enterprise:latest' is not available. Verify that all fields in the storage profile are correct.
ErrorCode: ImageNotFound
ErrorMessage: The platform image 'MicrosoftSQLServer:SQL2017-WS2016-BYOL:Enterprise:latest' is not available. Verify that all fields in the storage profile are correct.
StatusCode: 404
ReasonPhrase: Not Found
OperationID : faba9988-5d46-44cf-8414-261371159398
   ved System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   ved System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   ved System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   ved System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
    + PSComputerName        : localhost

**Comment by jrdbarnes** [comment]
I've seen the same issue, even when trying to force AutomatedLab to not use BYOL images by altering the script slightly:
`    'Add-LabMachineDefinition:AzureProperties' =  @{RoleSize = 'Standard_A2_v2';'UseByolImage' = 'False'}`

**Comment by nyanhp** [comment]
Hi, issue resolved by
```Update-Module AutomatedLab```, I had to implement a quick fix since in some (rare) instances the BYOL SQL image has been selected.

**Comment by GradualUnicycle** [comment]
I get the same error after the update: 

    Failed to create the following Azure machines: DSCCASQL01'. For further information take a look at the background job's result (Get-Job, Receive-Job)
At C:\Program Files\WindowsPowerShell\Modules\**AutomatedLab\5.0.2.4\**AutomatedLabVirtualMachines.psm1:99 char:9
+         throw "Failed to create the following Azure machines: $machin ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Failed to creat...b, Receive-Job):String) [], RuntimeException
    + FullyQualifiedErrorId : Failed to create the following Azure machines: DSCCASQL01'. For further information take a look at the background job's result (Get-Job, Receive-Job)


    One or more errors occured during VM creation.
System.Management.Automation.ActionPreferenceStopException: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The platform
 image '**MicrosoftSQLServer:SQL2017-WS2016-BYOL:Enterprise:latest' is not available**. Verify that all fields in the storage profile are correct.
ErrorCode: ImageNotFound
ErrorMessage: The platform image 'MicrosoftSQLServer:SQL2017-WS2016-BYOL:Enterprise:latest' is not available. Verify that all fields in the storage profile are correct.
StatusCode: 404
ReasonPhrase: Not Found

**Comment by jrdbarnes** [comment]
Seems to be working for me now, lab has progressed past the previous error.

**Comment by GradualUnicycle** [comment]
seems to be working here as well now. when i ran the update-module, it didn't update the AutomatedLabWorker module, so that was the problem
