### ISSUE TITLE
Master and dev builds fail.

### ISSUE THREAD

**Issue by nyanhp** [AutomatedLab/DscWorkshop#27]
Build.ps1 -ResolveDependency consistently fails for the master and dev branches.

## First error
```code
ERROR OCCURED DURING COMPILATION: At D:\temp\dscworkshop\DscSample\RootConfiguration.ps1:14 char:5
+     Import-DscResource -ModuleName PSDesiredStateConfiguration
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Could not find the module 'PSDesiredStateConfiguration'.
At D:\temp\dscworkshop\DscSample\RootConfiguration.ps1:14 char:5
+     Import-DscResource -ModuleName PSDesiredStateConfiguration
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Could not find the module 'PSDesiredStateConfiguration'.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : ModuleNotFoundDuringParse
```

## Second error

```code
ERROR: The specified module 'Microsoft.PowerShell.Management' was not loaded because no valid module file was found in any module directory.
At line:2 char:25
+ ...             Import-Module Microsoft.PowerShell.Management -Verbose:$f
```  

There have been no changes, the errors occur with a freshly cloned repository immediately.

I can confirm that this happens because PSModulePath is destroyed instead of simply being prepended with our build paths. Removing the line ```$env:PSModulePath = Join-Path -Path $PShome -ChildPath Modules``` fixes the issue.

We do not need to destroy the path if we simply prepend our additional paths. As soon as a valid module is picked up, everything is fine.

**Comment by gaelcolas** [comment]
I think it fails when initial execution of the build wasn't done with `-ResolveDependency`, and subsequent calls fails now that the PSModulePath has been changed. Clear session would work.

It's not great, but I think the intent was, despite poor execution, to clean up as much as possible the PSModulePath to avoid loading (automatically) undesired PowerShell modules.

The main issue it was trying to catch, iirc, was some bug with PackageManagement DSC resources that would always force-reload to version 1.0.0.1...
I don't think we're using this in the workshop, and I hope PowerShellGet do not have this issue anymore.

**Comment by raandree** [comment]
I cannot repro this. I have updated the references to the DSC Resources and the CommonTasks module today and the build process still works, see https://ci.appveyor.com/project/AutomatedLab/dscworkshop/builds/21745947.

I am going to work on the config in the next days to add some samples that are quite common and do match the lab config. The config we have right now compiles but does not work on the does.

**Comment by raandree** [comment]
I have just run another test. All worked well and I have moved the changes to the master branch. Tomorrow I will test the config on our TFS lab.

**Comment by nyanhp** [comment]
Well, for me it does not work in any way. @gaelcolas, I used ResolveDependency from the start and it hit me with Invoke-Pester not found...
I guess it's just on my machines then. I'll keep using my workaround.

**Comment by raandree** [comment]
Let's get connected via Skype the next days. I am quite confident we will be able to get it running on your box as well.

**Comment by nyanhp** [comment]
Closed as it is not reproducible and only affects one user.
