### ISSUE TITLE
Failed to create MOF files

### ISSUE THREAD

**Issue by fullenw1** [AutomatedLab/DscWorkshop#59]
After typing `.\Build.ps1 -ResolveDependency` no MOF has been created.
I got this type of error for each MOF:

`DSCFile01 : DSCFile01 : MOF__0.0.0 NA`
`    DSCFile01 : FileServer ::> FilesAndFolders .....................................................OK`
`    DSCFile01 : FileServer ::> RegistryValues ......................................................OK`
`    DSCFile01 : FileServer ::> SecurityBase ........................................................OK`
`    DSCFile01 : FileServer ::> WindowsFeatures .....................................................OK`
`    DSCFile01 : FileServer ::> NetworkIpConfiguration ..............................................OK`
`    DSCFile01 : FileServer ::> DscLcmController ....................................................OK`
`    DSCFile01 : FileServer ::> DscLcmMaintenanceWindows ............................................OK`
`    DSCFile01 : FileServer ::> DscTagging ..........................................................FAILED`
`        Compilation Error: System.Management.Automation.ParentContainsErrorRecordException: You cannot call a method on a null-valued expression..Message`
`Error occured during compilation of node 'DSCFile01' : Compilation errors occurred while processing configuration 'RootConfiguration'. Please review the errors reported in error stream and modify your configuration code appropriately.`
`Compilation errors occurred while processing configuration 'RootConfiguration'. Please review the errors reported in error stream and modify your configuration code appropriately.`
`At C:\Windows\System32\WindowsPowerShell\v1.0\Modules\PSDesiredStateConfiguration\PSDesiredStateConfiguration.psm1:3917 char:5`
`+     throw $ErrorRecord`
`+     ~~~~~~~~~~~~~~~~~~`
`    + CategoryInfo          : InvalidOperation: (RootConfiguration:String) [], InvalidOperationException`
`    + FullyQualifiedErrorId : FailToProcessConfiguration`
``
`PSDesiredStateConfiguration\Configuration : You cannot call a method on a null-valued expression.`
`At C:\Temp\DscWorkshop-dev\DscWorkshop-dev\DSC\DscConfigurations\CommonTasks\0.2.85\DSCResources\DscTagging\DscTagging.schema.psm1:1 char:1`
`+ Configuration DscTagging {`
`+ ~~~~~~~~~~~~~~~~~~~~~~~~~~`
`    + CategoryInfo          : InvalidOperation: (:) [Configuration], ParentContainsErrorRecordException`
`    + FullyQualifiedErrorId : InvokeMethodOnNull,Configuration`
``
`Exception calling "InvokeWithContext" with "2" argument(s): "You cannot call a method on a null-valued expression."`
`At C:\Windows\System32\WindowsPowerShell\v1.0\Modules\PSDesiredStateConfiguration\PSDesiredStateConfiguration.psm1:2232 char:13`
`+             $result = $Body.InvokeWithContext($functionsToDefine, $va ...`
`+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~`
`    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException`
`    + FullyQualifiedErrorId : RuntimeException`

**Comment by raandree** [comment]
Can you give us more details about how you called the script?

I have just cloned the repo, started the build script with 'ResolveDependency' and it worked right away. However, I remember to have fixed something that look like the error you are getting.

For now, please use the code in the dev branch. I am going to merge the latest working version to master very soon.

**Comment by fullenw1** [comment]
Hi Raymund!

Here is what I've done:

1. Downloaded the repository
2. Copied/pasted cmdlets from step 3. Setup your laptop
3. Launched `.build.ps1 -ResolveDependency`

Ok, waiting for your new master branch...
No hurry, it's just to learn how to use Datum.

**Comment by raandree** [comment]
Hi Luc,

Both branches should have a working version now. Can you give it another try, please?

**Comment by raandree** [comment]
Luc, while derlivering the DSC workshop @ PSConf.asia, we have seen the same issue that you are running to. It happens, if you download the project and not clone it. Please use

```
git clone https://github.com/automatedlab/dscworkshop
```

Working in a git repository is required because of this line: https://github.com/AutomatedLab/CommonTasks/blob/cf0973a3f62acd661a4eb201fc550c2792f5a771/CommonTasks/DscResources/DscTagging/DscTagging.schema.psm1#L34

**Comment by fullenw1** [comment]
It works fine with the command line.
Thanks Raymund!

I leave the issue opened as a reminder so you can decide if you want to improve the code to take into account the possibility to download the project or if you prefer to remove this possibility from the **2.Git clone your fork locally** section...

**Comment by raandree** [comment]
Good point, we will need to rework the main readme anyway. it is quite old and a lot has changed in the project. I leave the issue open until this is done.

**Comment by raandree** [comment]
This is now fixed in the 'DscTagging' resource. If the folder is not a Git repo, it write 'NoGitRepo' for the Commit Id.
