### ISSUE TITLE
Cannot find Operating System using eval iso

### ISSUE THREAD

**Issue by raandree** [AutomatedLab/DscWorkshop#6]
The ISO used is 14393.0.161119-1705.RS1_REFRESH_SERVER_EVAL_X64FRE_EN-US

The error is
![image](https://user-images.githubusercontent.com/11280760/38932670-342ac54c-4317-11e8-90ad-39376ac194e0.png)

- Can you please check the OS build your are running the deployment on?
- Can you mount the ISO using the Windows Explorer?
- Have you tried pointing Get-LabAvailableOperatingSystem directory to that image using the Path parameter?
- Get-LabAvailableOperatingSystem should at least return one OS.

@outek, FYI

**Comment by Outek** [comment]
Os Build is:
`PS C:\> [System.Environment]::OSVersion.Version

Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      16299  0


PS C:\>`

I can mount this ISO without any problems. I can start the setup.exe too

`PS C:\> Get-LabAvailableOperatingSystem -Path C:\LabSources\ISOs
14:59:07|00:05:57|00:05:34.850|   - found 1 OS images in the cache
14:59:07|00:05:57|00:05:34.861|   - Scanning 4 files for operating systemsFound 0 OS images.`

`PS C:\> Get-ChildItem C:\LabSources\ISOs


    Verzeichnis: C:\LabSources\ISOs


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----       18.04.2018     13:41     6972221440 14393.0.161119-1705.RS1_REFRESH_SERVER_EVAL_X64FRE_EN-US (1).ISO
-a----       17.04.2018     17:34     6972221440 14393.0.161119-1705.RS1_REFRESH_SERVER_EVAL_X64FRE_EN-US.ISO
-a----       18.04.2018     04:37             83 README.md
-a----       18.04.2018     09:27     1546242048 SQLServer2017-x64-ENU.iso
-a----       18.04.2018     08:39      671088640 tfsserver2018.2_rc2.iso`

**Comment by nyanhp** [comment]
@outek what happens when you
```Get-LabAvailableOperatingSystem -Verbose```

**Comment by nyanhp** [comment]
Last resort: Try Clear-LabCache.
If it does not work, @Raimund is preparing sticks in the presenter room

**Comment by mwtbadltr** [comment]
Do you have found a solution for using German OS and English ISO. Have also some trouble like this:

14:49:21|23:33:52|23:32:38.815|   - Scanning 1 files for operating systemsAUSFÜHRLICH: Mounting ISO image 'C:\Labsources\ISOs\14393.0.161119-1705.RS1_REFRESH_SERVER_EVAL_X64FRE_EN-US.ISO'
AUSFÜHRLICH: Getting disk image of the ISO
AUSFÜHRLICH: Got disk image 'E'
AUSFÜHRLICH: OS ISO mounted on drive letter 'E'
AUSFÜHRLICH: The Windows Image list contains 0 items
AUSFÜHRLICH: Dismounting ISO
Found 0 OS images.
AUSFÜHRLICH: Get-LabAvailableOperatingSystem...leaving...(Time elapsed: 00:00:00:190)

**Comment by mwtbadltr** [comment]
Sounds good, tried that version of code, one or two steps later...

PS C:\> Install-Lab
20:56:00|00:09:55|00:00:00.000|                       - Creating virtual networks
20:56:00|00:09:55|00:00:00.000|                         - Creating Hyper-V virtual network 'MyFirstLab'
20:56:00|00:09:55|00:00:00.087|                           - The network switch 'MyFirstLab' already exists
20:56:00|00:09:55|00:00:00.097|                           - Done
20:56:00|00:09:55|00:00:00.110|                         - done
20:56:00|00:09:55|00:00:00.000|                         - Creating base images
There isn't a single operating system ISO available in the lab. Please call 'Get-LabAvailableOperatingSystem' to see
what AutomatedLab has found and check the LabSources folder location by calling 'Get-LabSourcesLocation'.
In C:\Program Files\WindowsPowerShell\Modules\Automatedlab\5.0.2.24\AutomatedLabDisks.psm1:21 Zeichen:9
+         throw "There isn't a single operating system ISO available in ...

PS C:\> (Get-LAb).Sources
ISOs                                   AvailableOperatingSystems UnattendedXml
----                                   ------------------------- -------------
{783b8479-d605-4e57-b206-511e431ceda9} {}                        C:\AutomatedLabs


PS C:\> Get-LabAvailableOperatingSystem
21:04:07|00:18:02|00:08:07.279|                           - found 4 OS images in the cache


OperatingSystemName             : Windows Server 2016 Standard Evaluation
Version                         : 10.0.14393.0
PublishedDate                   : 16.07.2016 18:54:00
Size                            : 9235873810
Edition                         : ServerStandardEval
Installation                    : Server Core
AzureImageName                  :
VMWareImageName                 :
ProductKey                      : WC2BQ-8NRM3-FDDYY-2BFGV-KHKQY
IsoPath                         : C:\LabSources\ISOs\14393.0.161119-1705.RS1_REFRESH_SERVER_EVAL_X64FRE_EN-US.ISO
IsoName                         : 14393.0.161119-1705.RS1_REFRESH_SERVER_EVAL_X64FRE_EN-US
BaseDiskPath                    :
LinuxPackageGroup               : {}
LinuxType                       : SuSE
OperatingSystemType             : Windows
OperatingSystemImageName        : Windows Server 2016 Standard Evaluation
OperatingSystemImageDescription :
ImageIndex                      : 1
...................

Hope the output will help?

**Comment by mwtbadltr** [comment]
Don't know why, but now it seems to work quit correctly. That version works for me, thank you!

**Comment by raandree** [comment]
I am closing that issue and hope deployment issues are solved now. Please reopen the issue anytime if things do not work as expected.
